# frozen_string_literal: true

# Rakefile
require 'rspec/core/rake_task'

# Default task
task default: [:spec]

# RSpec task
RSpec::Core::RakeTask.new(:spec) do |task|
  task.pattern = 'spec/**/*_spec.rb'
end

# Lint task
task :lint do
  system('bundle exec rubocop .')
end
