name: Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Bundler Audit
      run: gem install bundler-audit
    - name: Run Bundler Audit
      run: bundler-audit check --update